experiment:
  seed: 42
  device: cuda
  deterministic: false
  data:
    path: src/data/trajectories/trajectories_m_3_n_3_LorenzSSM_data_T_200_N_500_r2_0.0dB_nu_-10.0dB.pkl
    batch_size: 64
    num_workers: 0
    pin_memory: false
    shuffle: true
  model:
    state_dim: 3
    obs_dim: 3
    dt: 0.02
    dynamics_hidden: 128
    dynamics_depth: 3
    measurement: linear
    transformer_d_model: 128
    transformer_nhead: 4
    transformer_layers: 3
  train:
    epochs: 200
    n_critic: 5
    warmup_epochs: 20
    lambda_innov: 1.0
    lambda_phys: 0.1
    lambda_adv: 0.1
    lambda_noise: 0.0
    lr_G: 0.001
    lr_D: 0.0005
    betas_G: [0.9, 0.999]
    betas_D: [0.9, 0.999]
    clip_norm: 1.0
    amp: false
    ema: false
  earlystop:
    window: 100
    ljungbox_lag: 20
    alpha: 0.05
    p_min: 0.05
    patience: 5
  logging:
    run_name: pi_gakf
    log_dir: runs/pi-gakf
    tensorboard: true
hydra:
  run:
    dir: runs/pi-gakf/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: pi_gakf_train
  output_subdir: null
