device: "cuda"
data:
  dataset_type: "LorenzSSM"
  n_states: 3
  n_obs: 3
  T: 200
  N_train: 1024
  N_val: 128
  inverse_r2_dB: 40.0
  nu_dB: 0.0
  dataset_path: "src/data/trajectories"
model:
  rnn: "GRU"
  hidden: 128
  layers: 2
  diag_cov: true
  lowrank: false
train:
  batch_size: 32
  steps: 50000
  lr_G: 0.001
  lr_D: 0.001
  betas: [0.5, 0.9]
  n_critic: 5
  gp_lambda: 10.0
  warm_epochs: 5
  rollout_K: 10
  lambda_rec: 1.0
  lambda_ms: 0.5
  lambda_innov: 0.2
  lambda_kf: 0.1
  lambda_apbm: 0.001
log:
  out_dir: "runs/gakf_lorenz_exp1"
  eval_every: 1000
  save_every: 5000
